name: Exercicio 1 - Data Atual - Danilo PEtroni
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  job1:
    name: Hora no Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Passo 1
        run: time

  job2:
    name: Hora no Windows
    runs-on: windows-latest
    steps:
      - name: Passo 1
        run: time

  job3:
    name: Hora no MAC
    runs-on: macos-latest
    steps:
      - name: Passo 1
        run: time

  job4:
    name: Job Dependente 
    steps:
      - name: Passo 1
        run: time
    needs: [job1, job2, job3]
